services:
  app:
    container_name: app_for_tests
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      DEBUG: "True"
