services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      - .:/src
    deploy:
      placement:
        constraints:
          - "node.labels.TAG==prod"
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 15s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: curl -sS http://127.0.0.1:8000/api/v1/public/healthcheck || echo 1
      interval: 30s
      timeout: 3s
      retries: 12